name: Main Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.0

    - name: Install dependencies
      run: bundle install

    - name: Run cleanup script
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: bundle exec ruby scripts/cleanup_projects.rb
